### ISSUE TITLE
Html Canvas

### ISSUE THREAD

**Issue by fishuke** [alekspopovic/pixel-art-drawing-editor#1]
I think better approach to drawing pixel canvas is using html canvas rather than divs. 
The problem with divs is and this approach is that when we have a big canvas (10kX10k) it goes crazy.
Using divs is not the only reason we are passing colors as props and its another performance issue.

**Comment by alekspopovic** [comment]
For sure, having a bunch of divs isn't optimal and the project certainly doesn't support having hundreds of thousands of divs. 🙂 This was intended as a prototype to spark some future ideas, and there are many ways to improve upon it, some of which I mention in my YouTube tutorial on this topic.

**Comment by fishuke** [comment]
Thank you for your kind reply.
